### ISSUE TITLE
Request:  No_input node

### ISSUE THREAD

**Issue by tsprivate** [cadavre/node-red-contrib-value-for#1]
Hi,

I just implemented your nodes and it is fitting great in my environment. I just have the below use-case and thought you might be able to modify your node or add a node for

- No-input-change for a while

Thanks for considering .. good work so far!!

**Comment by cadavre** [comment]
Hi,

Thanks! It's brand new nodes I created yesterday, so happy to see that already used by someone!

FYI I recently posted version 0.2.0 with some small changes (not breaking compatibility).

> no-input-change for a while

Would this cases work for you:
1) Each new value reported in given `for` duration was the same as first one.
2) No new values were reported after first one in given `for` time.

I so and it sound good – I can add such a node.

**Comment by cadavre** [comment]
Hi @tsprivate ! Library has got an update to 0.3 adding new node `fixed-for`. It compares current input to new input checking if value has changed or not – if not it will trigger first output. You can also select to start this od node (re)deployment for critical checks.

I guess it might solve your case. It isn't comparing messages timestamps, but if you set it to your required time – it will work for you as you expect, only new message with the same value won't restart the timer.
