### ISSUE TITLE
Request: Keep values stored in msg

### ISSUE THREAD

**Issue by Leonel-Toledo** [cadavre/node-red-contrib-value-for#2]
Hi,

  I have found this node very useful for monitor and trigger alarm events. However all information stored in msg is lost after using tihs node (Even "topic" field is lost). As a workaround, I have been including information after the node, but this is inconvenient.

  Thanks for the tool, and it will be wonderful if this behavior can be included.
  
    Best Regards,

**Comment by StreamSage** [comment]
Hey,

This nodes assume that value to compare is sent in `msg.payload`.

I can actually forward other (than `payload`) parts of the message to the output. But should it be latest message or first?

**Comment by Leonel-Toledo** [comment]
I didn though abuoout that.

 In tghe way I wish to use it. There would be fields to identify the source (maybe using topic, but more fileds could be included). This information will be the same in all messages.
 
   Now, for the purpose of the algoritm, it may be bettter to use last. That will allow for timestamps to be included, providing information of when the event was trigered. (Right now I included timestap in a sepparate node after the trigger)

**Comment by Leonel-Toledo** [comment]
I didn't thought about that.

In the way I wish to use it. There would be fields to identify the source (maybe using "topic", but other fileds should also be kept). This information will be the same in all messages.

Now, for the purpose of the algoritm, it may be bettter to use first message. That will allow for timestamps to be included, providing information of when the event was trigered. (Right now I included timestap in a node after the trigger, and this cause reported time to be a few seconds delayed)

**Comment by benganellison** [comment]
i would also like to have the first message, but i can see that the last one can also be relevant. could we have it configurable?

**Comment by cadavre** [comment]
@Leonel-Toledo @benganellison sorry guys it took so long, you're probably not even using this anymore, but I added requested feature. Now a whole message is forwarded to the output and you can select if it should be the most recent one (default) or the first one that triggered the timer.

**Comment by benganellison** [comment]
I'm still a grateful user. Thanks for adding
